apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8smaxreplicacount
  annotations:
    metadata.gatekeeper.sh/title: "Max Replica Count"
    metadata.gatekeeper.sh/version: 1.0.0
    description: "Restricts the replica count of Deployments to a specified maximum."
    argocd.argoproj.io/sync-wave: "1"
spec:
  crd:
    spec:
      names:
        kind: K8sMaxReplicaCount
      validation:
        openAPIV3Schema:
          type: object
          properties:
            maxReplicas:
              type: integer
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8smaxreplicacount

        # Luật: Phát hiện và chặn nếu số lượng bản sao (replicas) vượt quá giới hạn tối đa cho phép
        violation[{"msg": msg}] {
            # Lấy số lượng replica từ Spec của đối tượng yêu cầu (ví dụ: Deployment)
            replicas := input.review.object.spec.replicas
            # Lấy giới hạn replica tối đa từ tham số cấu hình
            max_replicas := input.parameters.maxReplicas
            # So sánh: nếu số replica lớn hơn giới hạn tối đa
            replicas > max_replicas
            # Trả về thông điệp báo lỗi vi phạm
            msg := sprintf("The deployment replicas count %v exceeds the maximum allowed limit of %v", [replicas, max_replicas])
        }
