apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: email-external-secret
  namespace: monitoring
spec:
  refreshInterval: "10s" # Tự động sync < 60s
  secretStoreRef:
    name: aws-store
    kind: SecretStore
  target:
    name: alertmanager-email # Tên K8s Secret được sinh ra cho Alertmanager
    creationPolicy: Owner
  data:
    - secretKey: password # Key password bên trong alertmanager-email secret
      remoteRef:
        key: email-password # Tên của Secret được lưu trên AWS Secrets Manager
