apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: email-external-secret
  namespace: monitoring
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: aws-store
    kind: SecretStore
  target:
    name: alertmanager-email
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: email-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
